openapi: 3.1.1
info:
  title: HafSQL API Documentations
  version: 1.0.0
  description: HafSQL installation guides are available at the [official GitLab repository](https://gitlab.com/mahdiyari/hafsql)
