import { pool } from '../helpers/database.ts'

export const setupOperationTables = async () => {
  using client = await pool.connect()
  for (const [name, value] of Object.entries(operationTables)) {
    let params = ''
    for (const [param, type] of Object.entries(value)) {
      params += `"${param}" ${type},\n`
    }
    await client.queryObject(
      `CREATE TABLE IF NOT EXISTS hafsql.operation_${name}_table (
        id int8,
        ${params}
        CONSTRAINT hafsql_operation_${name}_table_un UNIQUE (id)
    );`,
    )
  }
}

// varchar and varchar(n) have the same performance usually
// so varchar|text is recommended
const types = {
  varchar: 'varchar',
  jsonb: 'jsonb',
  int2: 'int2',
  int4: 'int4',
  int8: 'int8',
  hive_ammount: 'numeric(21, 3)',
  vests_ammount: 'numeric(27, 6)',
  timestamp: 'timestamp',
  boolean: 'boolean',
  rshares: 'numeric(27)',
}

// table name: `hafsq.operation_${name}_table`
// Describe table structure as an object
export const operationTables = {
  // vote: {
  //   voter: types.varchar,
  //   author: types.varchar,
  //   permlink: types.varchar,
  //   weight: types.int2,
  // },
  // comment: {
  //   author: types.varchar,
  //   permlink: types.varchar,
  //   parent_author: types.varchar,
  //   parent_permlink: types.varchar,
  //   title: types.varchar,
  //   body: types.varchar,
  //   json_metadata: types.jsonb,
  // },
  transfer: {
    from_account: types.varchar,
    to_account: types.varchar,
    amount: types.hive_ammount,
    symbol: types.varchar,
    memo: types.varchar,
  },
  transfer_to_vesting: {
    from_account: types.varchar,
    to_account: types.varchar,
    amount: types.hive_ammount,
    symbol: types.varchar,
  },
  withdraw_vesting: {
    account: types.varchar,
    vesting_shares: types.vests_ammount,
    symbol: types.varchar,
  },
  limit_order_create: {
    owner: types.varchar,
    orderid: types.int8,
    expiration: types.timestamp,
    amount_to_sell: types.hive_ammount,
    amount_to_sell_symbol: types.varchar,
    min_to_receive: types.hive_ammount,
    min_to_receive_symbol: types.varchar,
    fill_or_kill: types.boolean,
  },
  limit_order_cancel: {
    owner: types.varchar,
    orderid: types.int8,
  },
  feed_publish: {
    publisher: types.varchar,
    exchange_rate_base_amount: types.hive_ammount,
    exchange_rate_base_symbol: types.varchar,
    exchange_rate_quote_amount: types.hive_ammount,
    exchange_rate_quote_symbol: types.varchar,
  },
  convert: {
    owner: types.varchar,
    requestid: types.int8,
    amount: types.hive_ammount,
    symbol: types.varchar,
  },
  account_create: {
    fee: types.hive_ammount,
    fee_symbol: types.varchar,
    creator: types.varchar,
    new_account_name: types.varchar,
    owner: types.jsonb,
    active: types.jsonb,
    posting: types.jsonb,
    memo_key: types.varchar,
    json_metadata: types.jsonb,
  },
  account_update: {
    account: types.varchar,
    owner: types.jsonb,
    active: types.jsonb,
    posting: types.jsonb,
    memo_key: types.varchar,
    json_metadata: types.jsonb,
  },
  witness_update: {
    owner: types.varchar,
    url: types.varchar,
    block_signing_key: types.varchar,
    props_hbd_interest_rate: types.int4,
    props_maximum_block_size: types.int4,
    props_account_creation_fee: types.hive_ammount,
    props_account_creation_fee_symbol: types.varchar,
    fee: types.hive_ammount,
    symbol: types.varchar,
  },
  account_witness_vote: {
    account: types.varchar,
    witness: types.varchar,
    approve: types.boolean,
  },
  account_witness_proxy: {
    account: types.varchar,
    proxy: types.varchar,
  },
  pow: {
    worker_account: types.varchar,
    block_id: types.varchar,
    nonce: types.varchar,
    work: types.jsonb,
    props: types.jsonb,
  },
  custom: {
    required_auths: types.jsonb,
    custom_id: types.int8,
    data: types.varchar,
  },
  delete_comment: {
    author: types.varchar,
    permlink: types.varchar,
  },
  custom_json: {
    // required_auths: types.jsonb,
    // required_posting_auths: types.jsonb,
    // custom_id: types.varchar,
    // json: types.jsonb,
  },
  comment_options: {
    author: types.varchar,
    permlink: types.varchar,
    max_accepted_payout: types.hive_ammount,
    max_accepted_payout_symbol: types.varchar,
    percent_hbd: types.int2,
    allow_votes: types.boolean,
    allow_curation_rewards: types.boolean,
    extensions: types.jsonb,
  },
  set_withdraw_vesting_route: {
    from_account: types.varchar,
    to_account: types.varchar,
    percent: types.int2,
    auto_vest: types.boolean,
  },
  limit_order_create2: {
    owner: types.varchar,
    orderid: types.int8,
    amount_to_sell: types.hive_ammount,
    amount_to_sell_symbol: types.varchar,
    exchange_rate_base: types.hive_ammount,
    exchange_rate_base_symbol: types.varchar,
    exchange_rate_quote: types.hive_ammount,
    exchange_rate_quote_symbol: types.varchar,
    fill_or_kill: types.boolean,
    expiration: types.timestamp,
  },
  claim_account: {
    creator: types.varchar,
    fee: types.hive_ammount,
    symbol: types.varchar,
    extensions: types.jsonb,
  },
  create_claimed_account: {
    creator: types.varchar,
    new_account_name: types.varchar,
    owner: types.jsonb,
    active: types.jsonb,
    posting: types.jsonb,
    memo_key: types.varchar,
    json_metadata: types.jsonb,
    extensions: types.jsonb,
  },
  request_account_recovery: {
    recovery_account: types.varchar,
    account_to_recover: types.varchar,
    new_owner_authority: types.jsonb,
    extensions: types.jsonb,
  },
  recover_account: {
    account_to_recover: types.varchar,
    new_owner_authority: types.jsonb,
    recent_owner_authority: types.jsonb,
    extensions: types.jsonb,
  },
  change_recovery_account: {
    account_to_recover: types.varchar,
    new_recovery_account: types.varchar,
    extensions: types.jsonb,
  },
  escrow_transfer: {
    from_account: types.varchar,
    to_account: types.varchar,
    hbd_amount: types.hive_ammount,
    hive_amount: types.hive_ammount,
    escrow_id: types.int8,
    agent: types.varchar,
    fee: types.hive_ammount,
    fee_symbol: types.varchar,
    json_meta: types.jsonb,
    ratification_deadline: types.timestamp,
    escrow_expiration: types.timestamp,
  },
  escrow_dispute: {
    from_account: types.varchar,
    to_account: types.varchar,
    agent: types.varchar,
    who: types.varchar,
    escrow_id: types.int8,
  },
  escrow_release: {
    from_account: types.varchar,
    to_account: types.varchar,
    agent: types.varchar,
    who: types.varchar,
    receiver: types.varchar,
    escrow_id: types.int8,
    hbd_amount: types.hive_ammount,
    hive_amount: types.hive_ammount,
  },
  pow2: {
    work: types.jsonb,
    props: types.jsonb,
  },
  escrow_approve: {
    from_account: types.varchar,
    to_account: types.varchar,
    agent: types.varchar,
    who: types.varchar,
    escrow_id: types.int8,
    approve: types.boolean,
  },
  transfer_to_savings: {
    from_account: types.varchar,
    to_account: types.varchar,
    amount: types.hive_ammount,
    symbol: types.varchar,
    memo: types.varchar,
  },
  transfer_from_savings: {
    from_account: types.varchar,
    to_account: types.varchar,
    request_id: types.int8,
    amount: types.hive_ammount,
    symbol: types.varchar,
    memo: types.varchar,
  },
  cancel_transfer_from_savings: {
    from_account: types.varchar,
    request_id: types.int8,
  },
  decline_voting_rights: {
    account: types.varchar,
    decline: types.boolean,
  },
  claim_reward_balance: {
    account: types.varchar,
    reward_hive: types.hive_ammount,
    reward_hbd: types.hive_ammount,
    reward_vests: types.vests_ammount,
  },
  delegate_vesting_shares: {
    delegator: types.varchar,
    delegatee: types.varchar,
    vesting_shares: types.vests_ammount,
  },
  account_create_with_delegation: {
    creator: types.varchar,
    new_account_name: types.varchar,
    fee: types.hive_ammount,
    fee_symbol: types.varchar,
    delegation: types.vests_ammount,
    owner: types.jsonb,
    active: types.jsonb,
    posting: types.jsonb,
    memo_key: types.varchar,
    json_metadata: types.jsonb,
    extensions: types.jsonb,
  },
  witness_set_properties: {
    owner: types.varchar,
    props: types.jsonb,
    extensions: types.jsonb,
  },
  account_update2: {
    account: types.varchar,
    json_metadata: types.jsonb,
    posting_json_metadata: types.jsonb,
    extensions: types.jsonb,
  },
  create_proposal: {
    creator: types.varchar,
    receiver: types.varchar,
    subject: types.varchar,
    permlink: types.varchar,
    start_date: types.timestamp,
    end_date: types.timestamp,
    daily_pay: types.hive_ammount,
    daily_pay_symbol: types.varchar,
    extensions: types.jsonb,
  },
  update_proposal_votes: {
    voter: types.varchar,
    proposal_ids: types.jsonb,
    approve: types.boolean,
    extensions: types.jsonb,
  },
  remove_proposal: {
    proposal_owner: types.varchar,
    proposal_ids: types.jsonb,
    extensions: types.jsonb,
  },
  update_proposal: {
    proposal_id: types.int2,
    creator: types.varchar,
    daily_pay: types.hive_ammount,
    daily_pay_symbol: types.varchar,
    subject: types.varchar,
    permlink: types.varchar,
    extensions: types.jsonb,
  },
  collateralized_convert: {
    owner: types.varchar,
    requestid: types.int8,
    amount: types.hive_ammount,
    symbol: types.varchar,
  },
  recurrent_transfer: {
    from_account: types.varchar,
    to_account: types.varchar,
    amount: types.hive_ammount,
    symbol: types.varchar,
    memo: types.varchar,
    recurrence: types.int2,
    executions: types.int2,
    extensions: types.jsonb,
  },
  // Virtual Operations
  fill_convert_request: {
    owner: types.varchar,
    requestid: types.int8,
    amount_in: types.hive_ammount,
    amount_in_symbol: types.varchar,
    amount_out: types.hive_ammount,
    amount_out_symbol: types.varchar,
  },
  author_reward: {
    author: types.varchar,
    permlink: types.varchar,
    hbd_payout: types.hive_ammount,
    hive_payout: types.hive_ammount,
    vesting_payout: types.vests_ammount,
    curators_vesting_payout: types.vests_ammount,
    payout_must_be_claimed: types.boolean,
  },
  curation_reward: {
    curator: types.varchar,
    reward: types.vests_ammount,
    symbol: types.varchar,
    author: types.varchar,
    permlink: types.varchar,
    payout_must_be_claimed: types.boolean,
  },
  comment_reward: {
    author: types.varchar,
    permlink: types.varchar,
    payout: types.hive_ammount,
    author_rewards: types.hive_ammount,
    total_payout_value: types.hive_ammount,
    curator_payout_value: types.hive_ammount,
    beneficiary_payout_value: types.hive_ammount,
  },
  liquidity_reward: {
    owner: types.varchar,
    payout: types.hive_ammount,
    symbol: types.varchar,
  },
  interest: {
    owner: types.varchar,
    interest: types.hive_ammount,
    interest_symbol: types.varchar,
    is_saved_into_hbd_balance: types.boolean,
  },
  fill_vesting_withdraw: {
    from_account: types.varchar,
    to_account: types.varchar,
    withdrawn: types.vests_ammount,
    withdrawn_symbol: types.varchar,
    deposited: types.hive_ammount,
    deposited_symbol: types.varchar,
  },
  fill_order: {
    current_owner: types.varchar,
    open_owner: types.varchar,
    current_orderid: types.int8,
    open_orderid: types.int8,
    current_pays: types.hive_ammount,
    current_pays_symbol: types.varchar,
    open_pays: types.hive_ammount,
    open_pays_symbol: types.varchar,
  },
  shutdown_witness: {
    owner: types.varchar,
  },
  fill_transfer_from_savings: {
    from_account: types.varchar,
    to_account: types.varchar,
    request_id: types.int8,
    memo: types.varchar,
    amount: types.hive_ammount,
    symbol: types.varchar,
  },
  hardfork: {
    hardfork_id: types.int2,
  },
  comment_payout_update: {
    author: types.varchar,
    permlink: types.varchar,
  },
  return_vesting_delegation: {
    account: types.varchar,
    vesting_shares: types.vests_ammount,
  },
  comment_benefactor_reward: {
    benefactor: types.varchar,
    author: types.varchar,
    permlink: types.varchar,
    hbd_payout: types.hive_ammount,
    hive_payout: types.hive_ammount,
    vesting_payout: types.vests_ammount,
    payout_must_be_claimed: types.boolean,
  },
  producer_reward: {
    producer: types.varchar,
    vesting_shares: types.vests_ammount,
    vesting_shares_symbol: types.varchar,
  },
  clear_null_account_balance: {
    total_cleared: types.jsonb,
  },
  proposal_pay: {
    proposal_id: types.int2,
    receiver: types.varchar,
    payer: types.varchar,
    payment: types.hive_ammount,
    symbol: types.varchar,
  },
  dhf_funding: {
    treasury: types.varchar,
    additional_funds: types.hive_ammount,
    symbol: types.varchar,
  },
  hardfork_hive: {
    account: types.varchar,
    treasury: types.varchar,
    other_affected_accounts: types.jsonb,
    hive_transferred: types.hive_ammount,
    hbd_transferred: types.hive_ammount,
    vests_converted: types.vests_ammount,
    total_hive_from_vests: types.hive_ammount,
  },
  hardfork_hive_restore: {
    account: types.varchar,
    treasury: types.varchar,
    hbd_transferred: types.hive_ammount,
    hive_transferred: types.hive_ammount,
  },
  delayed_voting: {
    voter: types.varchar,
    votes: types.int8,
  },
  consolidate_treasury_balance: {
    total_moved: types.jsonb,
  },
  // effective_comment_vote: {
  //   voter: types.varchar,
  //   author: types.varchar,
  //   permlink: types.varchar,
  //   weight: types.rshares,
  //   rshares: types.rshares,
  //   total_vote_weight: types.rshares,
  //   pending_payout: types.hive_ammount,
  //   pending_payout_symbol: types.varchar,
  // },
  ineffective_delete_comment: {
    author: types.varchar,
    permlink: types.varchar,
  },
  dhf_conversion: {
    treasury: types.varchar,
    hive_amount_in: types.hive_ammount,
    hbd_amount_out: types.hive_ammount,
  },
  expired_account_notification: {
    account: types.varchar,
  },
  changed_recovery_account: {
    account: types.varchar,
    old_recovery_account: types.varchar,
    new_recovery_account: types.varchar,
  },
  transfer_to_vesting_completed: {
    from_account: types.varchar,
    to_account: types.varchar,
    hive_vested: types.hive_ammount,
    vesting_shares_received: types.vests_ammount,
  },
  pow_reward: {
    worker: types.varchar,
    reward: types.vests_ammount,
    symbol: types.varchar,
  },
  vesting_shares_split: {
    owner: types.varchar,
    vesting_shares_before_split: types.vests_ammount,
    vesting_shares_after_split: types.vests_ammount,
  },
  account_created: {
    new_account_name: types.varchar,
    creator: types.varchar,
    initial_vesting_shares: types.vests_ammount,
    initial_delegation: types.vests_ammount,
  },
  fill_collateralized_convert_request: {
    owner: types.varchar,
    requestid: types.int8,
    amount_in: types.hive_ammount,
    amount_in_symbol: types.varchar,
    amount_out: types.hive_ammount,
    amount_out_symbol: types.varchar,
    excess_collateral: types.hive_ammount,
    excess_collateral_symbol: types.varchar,
  },
  system_warning: {
    message: types.varchar,
  },
  fill_recurrent_transfer: {
    from_account: types.varchar,
    to_account: types.varchar,
    amount: types.hive_ammount,
    symbol: types.varchar,
    memo: types.varchar,
    remaining_executions: types.int2,
  },
  failed_recurrent_transfer: {
    from_account: types.varchar,
    to_account: types.varchar,
    amount: types.hive_ammount,
    symbol: types.varchar,
    memo: types.varchar,
    consecutive_failures: types.int2,
    remaining_executions: types.int2,
    deleted: types.boolean,
  },
  limit_order_cancelled: {
    seller: types.varchar,
    orderid: types.int8,
    amount_back: types.hive_ammount,
    symbol: types.varchar,
  },
  producer_missed: {
    producer: types.varchar,
  },
  proposal_fee: {
    creator: types.varchar,
    treasury: types.varchar,
    proposal_id: types.int2,
    fee: types.hive_ammount,
    fee_symbol: types.varchar,
  },
  collateralized_convert_immediate_conversion: {
    owner: types.varchar,
    requestid: types.int8,
    hbd_out: types.hive_ammount,
  },
  escrow_approved: {
    from_account: types.varchar,
    to_account: types.varchar,
    agent: types.varchar,
    escrow_id: types.int8,
    fee: types.hive_ammount,
    fee_symbol: types.varchar,
  },
  escrow_rejected: {
    from_account: types.varchar,
    to_account: types.varchar,
    agent: types.varchar,
    escrow_id: types.int8,
    hbd_amount: types.hive_ammount,
    hive_amount: types.hive_ammount,
    fee: types.hive_ammount,
    fee_symbol: types.varchar,
  },
  proxy_cleared: {
    account: types.varchar,
    proxy: types.varchar,
  },
}
